- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: 0567d444e59804edd
    zone_id: "AKIAUSZNFK5TLDBSPZKG"
    domain_name: "devopswithbnvst.uno"
    instnaces:
    - mongodb
  tasks: 
  - name: create ec2 user instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instnace_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output
  - name: print the e2c output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"
