- name: setup mongodb server
  hosts: redis
  become: yes
  tasks:
  - name: disabling deafult redis
    ansible.builtin.command: dnf module disable redis -y

  - name: enabling redis:7
    ansible.builtin.command: dnf module enable redis:7 -y

  - name: installing redis server
    ansible.builtin.package:
      name: redis
      state: present
  
  - name: allow remote connections
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: disabling protected mode
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: 'protected-mode yes'
      line: 'protected-mode no'

  - name: enabling and starting redis server
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes
  